## **Numpy**
----------

In [3]:
import numpy as np


**Why Numpy Instead Of List:**
1. Numpy is faster than List so we are using this one.
2. Numpy is built on C, C is a low level language whatever operations C performs that is more faster than python.
3. numpy is more efficient
4. Direct Operations on Numpy array (Which is also called as vectorization)
5. Python List allows mixed datatypes, but in case of numpy arrays it is homogeneous, It stores elemnt of same types.
6. Numpy Provides more built in functions compared to Lists.

In [3]:
np.array([1,2])

array([1, 2])

----------

### **Dimensions and Shape Of an Array**

##### **1) 32** - Scalar, 0Dimensional
##### **2) [1,2]** -1Dimensional
##### **3) [[1,2],[2,6]]** -2Dimensional

In [5]:
array1 = np.array(32)
array2 = np.array([1,2])
array3 = np.array([[1,2],[2,6]])

In [8]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

0
1
2


In [9]:
array1 = np.array([])
array2 = np.array([[]])
array3 = np.array([[[]]])

In [10]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


---------

### **Create Array**

#### **Method 1: Using arange**

In [11]:
array1 = np.arange(1,10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array1 = np.arange(1,10,2)
array1

array([1, 3, 5, 7, 9])

#### **Method 2: Using linspace**

In [16]:
array1 = np.linspace(0,10)
array1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
array1 = np.linspace(0,10,4)
array1

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

#### **Method 3: Array With all elements are Zero**

In [19]:
array1 = np.zeros(5)
array1

array([0., 0., 0., 0., 0.])

In [20]:
array2 = np.zeros([2,4])
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
array2 = np.zeros([2,4],dtype="int")
array2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### **Method 4: Array With all elements are Ones**

In [22]:
array1 = np.ones(5)
array1

array([1., 1., 1., 1., 1.])

In [24]:
array1 = np.ones([7,6],dtype="int")
array1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### **Method 5: Array Full of Any Value**

In [26]:
array1 = np.full(5,8)
array1

array([8, 8, 8, 8, 8])

In [27]:
array1 = np.full([2,6],8)
array1

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [28]:
array1 = np.full([2,6],6.7)
array1

array([[6.7, 6.7, 6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7, 6.7, 6.7]])

#### **Method 6: Random Floats 0 to 1**

In [36]:
array1 = np.random.rand(10)
array1

array([0.31257336, 0.62588048, 0.1113093 , 0.49147779, 0.94089409,
       0.05200627, 0.72680887, 0.97585428, 0.42178215, 0.58754642])

In [35]:
array1 = np.random.rand(2,2)
array1

array([[0.29258267, 0.79830164],
       [0.9752543 , 0.37986269]])

#### **Method 7: Random Integers**

In [43]:
array1 = np.random.randint(1,100)
array1

17

In [44]:
array1 = np.random.randint(1,100,size=(2,2))
array1

array([[49, 70],
       [73, 52]])

----------

### **Numpy Data Types and Type Casting**

In [45]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [46]:
array1 = np.array([1,2,3.2,4])
array1

array([1. , 2. , 3.2, 4. ])

In [49]:
lst = ["string",1,2,6.7]
array = np.array(lst)
print(array)
print(array.dtype)

['string' '1' '2' '6.7']
<U32


In [52]:
array1 = np.array([1,2,4],dtype="float64")
print(array1)
print(array1.dtype)

[1. 2. 4.]
float64


In [53]:
array1 = np.array([1.2,2.2,4],dtype="int64")
print(array1)
print(array1.dtype)

[1 2 4]
int64


-----------

### **Type Casting: Using astype()**

In [57]:
array1 = np.array([1,2,4])
print(array1)
new_array = array1.astype('float64')
print(new_array)

[1 2 4]
[1. 2. 4.]


-----------

### **Array Reshaping --> Reshape, Ravel, Flatten**

#### **Reshape**

In [61]:
array1 = np.array([1,2,3,4,5,6])
reshaped1 = array1.reshape(2,3)
print(reshaped1)

[[1 2 3]
 [4 5 6]]


In [59]:
array1 = np.array([1,2,3,4])
reshaped = array1.reshape(2,2)
print(reshaped)

[[1 2]
 [3 4]]


#### **Ravel**

- Convert to 1D Array

In [63]:
ravel1 = reshaped1.ravel()
ravel1

array([1, 2, 3, 4, 5, 6])

#### **Flatten**

In [65]:
flat = reshaped1.flatten()
flat

array([1, 2, 3, 4, 5, 6])

---------

### **Arithmetic Operations on Arrays**

In [66]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [68]:
# Addition
print(array1+array2)

[5 7 9]


In [69]:
# Subtraction
print(array1-array2)

[-3 -3 -3]


In [70]:
# Multiplication
print(array1*array2)

[ 4 10 18]


In [71]:
# Division
print(array1/array2)

[0.25 0.4  0.5 ]


In [73]:
# Integer Division
print(array1//array2)

[0 0 0]


In [75]:
# Modulus
print(array2%array1)

[0 1 0]


In [76]:
# Exponent --> Power
print(array1**2)

[1 4 9]


### **Universal Functions**

In [77]:
print(np.sqrt(array1))

[1.         1.41421356 1.73205081]


In [79]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


-----------------

### **Indexing and Slicing**

In [80]:
array1 = np.array([1,2,4,5,6,7,8,9,10])

In [81]:
array1[0]

1

In [82]:
array1[-1]

10

In [83]:
array1[0:4]

array([1, 2, 4, 5])

In [84]:
array1[0:4:2]

array([1, 4])

In [85]:
array1[-1:-4:-1]

array([10,  9,  8])

In [87]:
array1[-1::-2]

array([10,  8,  6,  4,  1])

In [88]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2])

[[1 2 3]
 [4 5 6]]


In [89]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,:1])

[[1]
 [4]]


#### **Transpose**

In [90]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### **Concatenation - vstack and hstack**

In [92]:
array1 = np.array([1,2])
array2 = np.array([3,4])
new_array = np.vstack([array1,array2])
new_array

array([[1, 2],
       [3, 4]])

In [95]:
array1 = np.array([1,2])
array2 = np.array([3,4])
new_array = np.hstack([array1,array2])
new_array

array([1, 2, 3, 4])

-----

### **Splitting Of an Array**

In [4]:
array1 = np.array([[1,2,3,4,5,6],
                   [7,8,9,10,11,12],
                   [13,14,15,16,17,18],
                   [19,20,21,22,23,24],
                   [25,26,27,28,29,30],
                   [31,32,33,34,35,36]])
array1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [5]:
print(np.split(array1,6))

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36]])]


In [6]:
print(np.split(array1,2))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])]


In [7]:
print(np.hsplit(array1,2))

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27],
       [31, 32, 33]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])]


In [8]:
print(np.vsplit(array1,2))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])]


--------
### **Repeating**
- It Repeats Each Element 

In [9]:
array1 = np.array([1,2,4])
print(np.repeat(array1,2))

[1 1 2 2 4 4]


In [10]:
print(np.repeat(array1,4))

[1 1 1 1 2 2 2 2 4 4 4 4]


### **tile**

- It Repeats Whole Array

In [11]:
print(np.tile(array1,2))

[1 2 4 1 2 4]


In [12]:
print(np.repeat(array1,4))

[1 1 1 1 2 2 2 2 4 4 4 4]


-----

### **Aggregate Functions**
- It is Used to Summarize the array.

In [13]:
array1 = np.array([[1,2,3,4,5,6],
                   [7,8,9,10,11,12],
                   [13,14,15,16,17,18],
                   [19,20,21,22,23,24],
                   [25,26,27,28,29,30],
                   [31,32,33,34,35,36]])
array1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [14]:
print(np.sum(array1))

666


In [15]:
# Average
print(np.mean(array1))

18.5


In [16]:
print(np.median(array1))

18.5


In [17]:
print(np.std(array1))

10.388294694831615


In [18]:
print(np.var(array1))

107.91666666666667


In [19]:
print(np.min(array1))

1


In [20]:
print(np.max(array1))

36


In [22]:
# Row Wise Sum
print(np.sum(array1,axis=0))

[ 96 102 108 114 120 126]


In [23]:
# Column Wise Sum
print(np.sum(array1,axis=1))

[ 21  57  93 129 165 201]


----------
### **Cumulative Operations**
- These are used to calculate running total.

In [24]:
array1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [25]:
print(np.cumsum(array1))

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276 300 325 351 378 406 435 465 496 528 561 595 630 666]


In [26]:
print(np.cumprod(array1))

[          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736 -1195114496  -522715136   862453760  -775946240
  2076180480 -1853882368  1484783616 -1375731712 -1241513984  1409286144
   738197504 -2147483648 -2147483648           0           0           0]


-----------
### **Conditional Based Choices**

In [35]:
array = np.array([[1,2],[10,20]])

In [36]:
# Where

In [37]:
result = np.where(array1<10,"low","high")
result

array([['low', 'low', 'low', 'low', 'low', 'low'],
       ['low', 'low', 'low', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high']], dtype='<U4')

In [38]:
# For Value That are greater than 15 and less than 35
result1 = np.logical_and(array1>15,array1<35)
result1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False]])

In [40]:
print(np.argwhere(array>5))

[[1 0]
 [1 1]]


In [42]:
# For Value That are greater than 15 or less than 35
result1 = np.logical_or(array1>15,array1>20)
result1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

----------

### **BroadCasting**
- It means stretching the smaller array to match the shape of the bigger array
- Numpy compares the shapes of the arrays from the end (right to left) and follow these rules:
#### **Rules**
**1.** If Shapes are equal they are compatible.</br>
**2.** If one is 1, It can be stretched to match the other.</br>
**3.** If shapes are different Not 1 or equal --> Error

In [44]:
array1 = np.array([[100,200],[400,600]])
array2 = array1 + 50

In [47]:
print(array2)
print(array2.shape)

[[150 250]
 [450 650]]
(2, 2)


-------------------

### **Vectorization**
- Replacing Loops operations with single function
- np.vectorize() --> Convert a regular function to be applied on an array.

**It is Used**
- When you apply a custom function to every element
- For readability
- It is not faster than loop
- It only makes syntax cleaner, but doesnot improve speed like real vectorized numpy functions.

In [48]:
def square(x):
    return x*x
vfunc = np.vectorize(square)

In [50]:
vfunc(array1)

array([[ 10000,  40000],
       [160000, 360000]])

-----------
### **Handling Missing Values**


In [51]:
array1 = np.array([1,2,np.nan,4])
array1

array([ 1.,  2., nan,  4.])

In [52]:
# np.inf and -np.inf --> Represents Positive and Negative Infinites

In [53]:
array1 = np.array([1,2,np.inf,4])
array1

array([ 1.,  2., inf,  4.])

In [54]:
# np.isnan
# np.isinf
# np.isinfinite

# These are Functions Used to detect any null values, finite or infinite values

In [55]:
array1 = np.array([1,2,np.nan,4])
np.isnan(array1)

array([False, False,  True, False])

In [60]:
array2 = np.array([1,2,np.inf,4])
np.isinf(array2)

array([False, False,  True, False])

In [61]:
array4 = np.nan_to_num(array1)
array4

array([ 1.00000000e+000,  2.00000000e+000, -1.79769313e+308,
        4.00000000e+000])

AttributeError: module 'numpy' has no attribute 'isinfinite'